apiVersion: v1
kind: ConfigMap
metadata:
  name: hadoop-config
  namespace: hadoop
data:
  core-site: |
    <?xml version="1.0" encoding="UTF-8"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <!-- Put site-specific property overrides in this file. -->

    <configuration>
      <property>
        <name>fs.defaultFS</name>
        <value>hdfs://namenode:9000/</value>
      </property>
      <property>
          <name>hadoop.native.lib</name>
          <value>true</value>
      </property>
    </configuration>
  hdfs-site: |
    <?xml version="1.0" encoding="UTF-8"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <!-- Put site-specific property overrides in this file. -->

    <configuration>
      <!-- namenode config -->
      <property>
        <name>dfs.namenode.name.dir</name>
        <value>/hadoop/dfs/name</value>
      </property>

      <!-- datanode config -->
      <property>
        <name>dfs.replication</name>
        <value>1</value>
      </property>
      <property>
        <name>dfs.datanode.data.dir</name>
        <value>/hadoop/dfs/data</value>
      </property>
    </configuration>
  yarn-site: |
    <?xml version="1.0"?>
    <configuration>

      <!-- resourcemanager and nodemanager shared -->
      <property>
        <name>yarn.acl.enable</name>
        <value>false</value>
      </property>
      <property>
        <name>yarn.admin.acl</name>
        <value>*</value>
      </property>
      <property>
        <name>yarn.log-aggregation-enable</name>
        <value>false</value>
      </property>

      <!-- resourcemanager configuration -->
      <property>
        <name>yarn.resourcemanager.hostname</name>
        <value>resourceManager</value>
      </property>

      <!-- nodemanager configuration -->
      <property>
        <name>yarn.nodemanager.local-dirs</name>
        <value>/tmp</value>
      </property>

      <property>
        <name>yarn.nodemanager.log-dirs</name>
        <value>/log</value>
      </property>

      <property>
        <name>yarn.nodemanager.vmem-check-enabled</name>
        <value>false</value>
      </property>

    </configuration>
