apiVersion: v1
kind: Service
metadata:
  name: namenode
  namespace: hadoop
  labels:
    app: hadoop-namenode
    tier: persistence
    version: v1
spec:
  selector:
    app: hadoop-namenode
    tier: persistence
    version: v1
  ports:
  - name: http-service
    port: 50070
    targetPort: 50070
  - name: client-rpc
    port: 9000
    targetPort: 9000
